CREATE TABLE IF NOT EXISTS productos (
  "idProducto" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombreProducto" VARCHAR(255) NOT NULL,
  "descripcionProducto" VARCHAR(255),
  "precioProducto" INTEGER NOT NULL,
  "stockProducto" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS venta (
  id_venta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  direccion_compra VARCHAR(255) NOT NULL,
  valor_compra INTEGER NOT NULL,
  fecha_compra DATE NOT NULL,
  despacho_generado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS despachos (
  id_despacho BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  fecha_despacho DATE,
  patente_camion VARCHAR(20),
  intento INTEGER NOT NULL DEFAULT 1,
  id_compra BIGINT NOT NULL,
  direccion_compra VARCHAR(255),
  valor_compra BIGINT,
  entregado BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_despachos_venta
    FOREIGN KEY (id_compra)
    REFERENCES venta (id_venta)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

INSERT INTO productos ("idProducto", "nombreProducto", "descripcionProducto", "precioProducto", "stockProducto")
VALUES
  (1, 'Notebook Pro 14', 'Notebook para uso profesional', 1299000, 15),
  (2, 'Mouse Inalambrico', 'Mouse ergonomico recargable', 29990, 80),
  (3, 'Teclado Mecanico', 'Teclado switch blue', 69990, 45)
ON CONFLICT ("idProducto") DO NOTHING;

INSERT INTO venta (id_venta, direccion_compra, valor_compra, fecha_compra, despacho_generado)
VALUES
  (1001, 'Av. Libertador 100, Santiago', 1299000, DATE '2026-05-20', TRUE),
  (1002, 'Calle Los Leones 245, Providencia', 99980, DATE '2026-05-21', TRUE),
  (1003, 'Pasaje Andino 55, Puente Alto', 69990, DATE '2026-05-22', FALSE)
ON CONFLICT (id_venta) DO NOTHING;

INSERT INTO despachos (id_despacho, fecha_despacho, patente_camion, intento, id_compra, direccion_compra, valor_compra, entregado)
VALUES
  (5001, DATE '2026-05-23', 'ABCD12', 1, 1001, 'Av. Libertador 100, Santiago', 1299000, TRUE),
  (5002, DATE '2026-05-24', 'EFGH34', 2, 1002, 'Calle Los Leones 245, Providencia', 99980, FALSE)
ON CONFLICT (id_despacho) DO NOTHING;
